apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.inputs.nginxService.name }}
spec:
  type: {{ .Values.inputs.nginxService.type }}
  selector:
    app: blog-nginx
  ports:
  - port: {{ .Values.inputs.nginxService.ports.port }}
    targetPort: {{ .Values.inputs.nginxService.ports.targetPort }}