apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.inputs.dbService.name }}
spec:
  type: {{ .Values.inputs.dbService.type }}
  selector:
    app: postgres
  ports:
  - port: {{ .Values.inputs.dbService.ports.port }}
    targetPort: {{ .Values.inputs.dbService.ports.targetPort }}