apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.inputs.blogDeploy.hpa.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.inputs.blogDeploy.name }}
  minReplicas: {{ .Values.inputs.blogDeploy.hpa.minReplicas }}
  maxReplicas: {{ .Values.inputs.blogDeploy.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.inputs.blogDeploy.hpa.averageCPUUtilization }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.inputs.blogDeploy.hpa.averageMemoryUtilization }}