apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.inputs.blogService.name }}
spec:
  type: {{ .Values.inputs.blogService.type }}
  selector:
    app: blog
  ports:
  - port: {{ .Values.inputs.blogService.ports.port }}
    targetPort: {{ .Values.inputs.blogService.ports.targetPort }}