apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.inputs.clusterIssuer.name }}
spec:
  acme:
    # Email address used for ACME registration
    email: {{ .Values.inputs.clusterIssuer.email }}
    server: {{ .Values.inputs.clusterIssuer.server }}
    privateKeySecretRef:
      # Name of a secret used to store the ACME account private key
      name: {{ .Values.inputs.clusterIssuer.secretName }}
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - http01:
        ingress:
          class: nginx